apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collab-api
  template:
    metadata:
      labels:
        app: collab-api
    spec:
      containers:
      - name: collab-api
        image: madhurlak/collabapi:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-cred
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-cred
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-cred
              key: aws_default_region
---
apiVersion: v1
kind: Service
metadata:
  name: collab-service
spec:
  selector:
    app: collab-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30004
  type: NodePort