apiVersion: apps/v1
kind: Deployment
metadata:
  name: input-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: input-api
  template:
    metadata:
      labels:
        app: input-api
    spec:
      containers:
      - name: input-api
        image: madhurlak/inputapi:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-cred
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-cred
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-cred
              key: aws_default_region
---
apiVersion: v1
kind: Service
metadata:
  name: input-service
spec:
  selector:
    app: input-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30002
  type: NodePort
