apiVersion: v1
kind: Service
metadata:
  name: colab-app-service
spec:
  selector:
    app: colab-app  # Must match the app label in the deployment.yaml
  ports:
    - protocol: TCP
      port: 80       # Port the service will be exposed on
      targetPort: 8000  # Port the container is running on
  type: LoadBalancer  # Expose your app externally, change to NodePort if LoadBalancer is not available
